### ISSUE TITLE
supergroups not updating if app is closed

### ISSUE THREAD

**Issue by legacychimera247** [CODeRUS/harbour-sailorgram#10] opened 2017-03-03 09:48 UTC
as the title says supergroups only receive new messages if the app is already opened...if not it only load latest message...

**Comment by CODeRUS** [comment] 2017-03-03 10:10
EXPLAIN! :dalek:

**Comment by legacychimera247** [comment] 2017-03-03 10:29
if the app is closed and then i open the app, all supergroups will show no new messages at allor only latest message written...if the app is opened it receive messages normally...praticalluy if someone from a supergroup write something while the app is closed that message is lost as sailorgram will not show it (they are correctly shown in telegram anyway)

**Comment by CODeRUS** [comment] 2017-03-03 10:34
never experienced this and can't reproduce.

**Comment by legacychimera247** [comment] 2017-03-03 12:13
i've made screenshot to make you understand...this one is the same chat at the same time in sailorgram
https://1drv.ms/i/s!AlyMkCypv00qgrRE80iW0SAvB0lhCw
this one is the same chat in telegram for android
https://1drv.ms/i/s!AlyMkCypv00qgrRF42TeezQv8ucMHA

as you may see there are messages missing in sailorgram and generally it misses all of the messages when closed...

**Comment by CODeRUS** [comment] 2017-03-03 12:22
i can't see your screenshots by these links

**Comment by legacychimera247** [comment] 2017-03-03 13:42
sorry...here it is...this is sailorgram
https://1drv.ms/i/s!AlyMkCypv00qgrRG7bkNuChsv97nTw
this is telegram
https://1drv.ms/i/s!AlyMkCypv00qgrRHmRVSjzD0RDBSWg

**Comment by CODeRUS** [comment] 2017-03-03 14:13
i see, but i never experienced this. don't even know how to understand what can be wrong.

**Comment by legacychimera247** [comment] 2017-03-03 15:00
unfortunately this is present since dax versions and doing a clean reinstall didn't solve the issue...

**Comment by CODeRUS** [comment] 2017-03-14 15:29
fixed in v0.9.7

**Closed by CODeRUS** 2017-03-14 15:29 UTC
Labels: bug
